services:
  db:
    image: postgres:15-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: chatdb
      POSTGRES_USER: chatuser
      POSTGRES_PASSWORD: chatpass
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7-alpine
    restart: unless-stopped
    ports: ["6379:6379"]

  chat_project:
    build: ./chat_project
    volumes:
      - ./chat_project:/app
    depends_on:
      - db
      - redis
    ports:
      - "8000:8000"
    environment:
      DJANGO_SETTINGS_MODULE: chat_project.settings
      REDIS_URL: redis://redis:6379
      DATABASE_URL: postgres://chatuser:chatpass@db:5432/chatdb   # ← EKLENDİ

  frontend:
    build: ./frontend
    ports:
      - "5173:80"
    depends_on:
      - chat_project


volumes:
  postgres_data:
